### ISSUE TITLE
Error setting up entry {ADDRESS}

### ISSUE THREAD

**Issue by AngelFreak** [briis/renoweb#1]
When i try to setup the integration after install through HACS, i get the following error, and no data:
```
Logger: homeassistant.config_entries
Source: custom_components/renoweb/__init__.py:86
First occurred: 7:54:10 PM (2 occurrences)
Last logged: 8:07:25 PM

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/renoweb/__init__.py", line 86, in async_setup_entry
    await renoweb.get_pickup_data()
  File "/usr/local/lib/python3.8/site-packages/pyrenoweb/client.py", line 187, in get_pickup_data
    next_pickup = datetime.date.fromtimestamp(int(row.get("nextpickupdatetimestamp")))
ValueError: invalid literal for int() with base 10: ''
```

Let me know if you need anything from me.

**Comment by briis** [comment]
Seems like I don’t get a numeric time stamp for your address, and then it fails when I try to convert to a date. I know you can extract the raw data yourself. Would be helpful if you could do this, and post it here - or mail me your address on Bjarne@briis.com. Then I can check the raw data and see why the data for your address is different from mine.

**Comment by briis** [comment]
Hi again,
I found an address that gives the same error, so I now have something to test with. Stay tuned and I will fix this

**Comment by briis** [comment]
There is now a release 0.1.2, that should fix this. Please report back if you get the right number of sensors and verify that the dates are correct.

**Comment by msvinth** [comment]
Works for me now. Got the expected sensors and days. 👍

**Comment by AngelFreak** [comment]
Works like a charm!
Fantastic work.

Please feel free to reach out to me if you need something.

**Comment by AngelFreak** [comment]
Works like a charm!
Fantastic work.

Please feel free to reach out to me if you need something.

**Comment by briis** [comment]
Great it works now. When/If the API changes and/or the API keys changes, I will need your help in sniffing out this again. Thanks.
