### ISSUE TITLE
XYZ implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by LordMike** [briis/renoweb#10]
Jeg har omsider fundet ud af at feltet blot har skiftet navn - se: https://github.com/home-assistant/core/pull/47304

- Entity sensor.renoweb_haveaffald_henteordning (<class 'custom_components.renoweb.sensor.RenoWebSensor'>) implements device_state_attributes. Please report it to the custom component author.
- Entity sensor.renoweb_haveaffald_minicontainer_360_l_tommes_via_haveaffaldsruten (<class 'custom_components.renoweb.sensor.RenoWebSensor'>) implements device_state_attributes. Please report it to the custom component author.
- Entity sensor.renoweb_opgrab_haveaffald (<class 'custom_components.renoweb.sensor.RenoWebSensor'>) implements device_state_attributes. Please report it to the custom component author.
- Entity sensor.renoweb_udbringning (<class 'custom_components.renoweb.sensor.RenoWebSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by briis** [comment]
Det er korrekt, det skal nu være `extra_state_attributes`. Jeg fixer det i dag.

**Comment by briis** [comment]
Har lige udgivet 0.1.14, som skulle fixe dette.

**Comment by LordMike** [comment]
Advarslen er forduftet. :)
