### ISSUE TITLE
To adresser

### ISSUE THREAD

**Issue by merrild4** [briis/renoweb#11]
Hej Briis

Kan man lave det med 2 forskellige adresser i forskellige kommuner ?

eks. Hjemme og i sommerhuset ?

**Comment by briis** [comment]
Hej,
Ja det kan du sagtens. Du tilføjer bare Integrationen en gang til, og skriver så den anden adresse ind her. Du får så nye sensorer i systemet. Vær opmærksom på at de kan hedde det samme som de tidligere men får så bare et `_2` efter sig i navnet.

**Comment by merrild4** [comment]
Mange tak. Virker perfekt 👍🏼
