### ISSUE TITLE
HA 2022.04.3  RenoWeb Garbage Collection failing.

### ISSUE THREAD

**Issue by kejXero** [briis/renoweb#14]
After update to HA 2022.04.3 i discovered that RenoWeb Garbage Collection was failing. 'i am not a 100 percent sure that it happend when updating but it was here i discovered the failure. 

renoweb.async_setup_entry did not return boolean
April 13, 2022, 8:27:54 PM – (ERROR) config_entries.py
Error occured: Error requesting data from https://servicesgh.renoweb.dk/v1_13: 500, message='Internal Server Error', url=URL('https://servicesgh.renoweb.dk/v1_13/GetJSONContainerList.aspx?municipalitycode=0159&apikey=346B43B0-D1F0-4AFC-9EE8-C4AD1BFDC218&adressId=22423&fullinfo=1&supportsSharedEquipment=1')
April 13, 2022, 8:27:54 PM – (ERROR) RenoWeb Garbage Collection (custom integration)

**Comment by briis** [comment]
It seemed the backend of Renoweb was down yesterday. I just restarted my HA and now it works again.

**Comment by kejXero** [comment]
Og nu virker det også her :-)

Med venlig hilsen

Henrik
________________________________

**Comment by StryxDK** [comment]
![image](https://user-images.githubusercontent.com/73670792/164175418-c170c165-448e-4ea9-9646-0e2fa2174247.png)
Kan ikke kontakte renoweb skiver den i log'en

**Comment by briis** [comment]
Som skrevet ovenfor, er det et problem med at forbindelsen til Renoweb, som ligger udenfor min kontrol. Min egen opsætning virker fint lige nu, men jeg er også løbet ind i dette problem tidligere.

**Comment by apollo14dk** [comment]
Ved du om Faxe kommune kan bruges, for ved de bruger renoweb.

**Comment by briis** [comment]
Der må være mere end 1 implementering da Faxe ikke virker. Nedenfor er listen over kommuner der returneres på det API jeg bruger, og det er dem jeg ved virker. Jeg har testet med Faxe,men kan ikke få det til at virke. Beklager.

MUNICIPALITY LIST
**************************
1: Aalborg - ID: 851
2: Allerød - ID: 201
3: Brøndby - ID: 153
4: Dragør - ID: 155
5: Egedal - ID: 240
6: Esbjerg - ID: 561
7: Fredensborg - ID: 210
8: Frederikssund - ID: 250
9: Gentofte - ID: 157
10: Gladsaxe - ID: 159
11: Glostrup - ID: 161
12: Greve - ID: 253
13: Halsnæs - ID: 260
14: Helsingør - ID: 217
15: Herlev - ID: 163
16: Hillerød - ID: 219
17: Hvidovre - ID: 167
18: Høje-Taastrup - ID: 169
19: Køge - ID: 259
20: Lejre - ID: 350
21: Lyngby-Taarbæk - ID: 173
22: Rebild - ID: 840
23: Ringkøbing-Skjern - ID: 760
24: Roskilde - ID: 265
25: Rudersdal - ID: 230
26: Samsø - ID: 741
27: Solrød - ID: 269
28: Stevns - ID: 336
29: Svendborg - ID: 479
30: Sweco Demo - ID: 10210
31: Sweco Test - ID: 10730
32: Sweco Test T - ID: 20161
33: Tårnby - ID: 185
34: Vejen - ID: 575

**Comment by apollo14dk** [comment]
> Der må være mere end 1 implementering da Faxe ikke virker. Nedenfor er listen over kommuner der returneres på det API jeg bruger, og det er dem jeg ved virker. Jeg har testet med Faxe,men kan ikke få det til at virke. Beklager.
> 
> 
> 
> MUNICIPALITY LIST
> 
> **************************
> 
> 1: Aalborg - ID: 851
> 
> 2: Allerød - ID: 201
> 
> 3: Brøndby - ID: 153
> 
> 4: Dragør - ID: 155
> 
> 5: Egedal - ID: 240
> 
> 6: Esbjerg - ID: 561
> 
> 7: Fredensborg - ID: 210
> 
> 8: Frederikssund - ID: 250
> 
> 9: Gentofte - ID: 157
> 
> 10: Gladsaxe - ID: 159
> 
> 11: Glostrup - ID: 161
> 
> 12: Greve - ID: 253
> 
> 13: Halsnæs - ID: 260
> 
> 14: Helsingør - ID: 217
> 
> 15: Herlev - ID: 163
> 
> 16: Hillerød - ID: 219
> 
> 17: Hvidovre - ID: 167
> 
> 18: Høje-Taastrup - ID: 169
> 
> 19: Køge - ID: 259
> 
> 20: Lejre - ID: 350
> 
> 21: Lyngby-Taarbæk - ID: 173
> 
> 22: Rebild - ID: 840
> 
> 23: Ringkøbing-Skjern - ID: 760
> 
> 24: Roskilde - ID: 265
> 
> 25: Rudersdal - ID: 230
> 
> 26: Samsø - ID: 741
> 
> 27: Solrød - ID: 269
> 
> 28: Stevns - ID: 336
> 
> 29: Svendborg - ID: 479
> 
> 30: Sweco Demo - ID: 10210
> 
> 31: Sweco Test - ID: 10730
> 
> 32: Sweco Test T - ID: 20161
> 
> 33: Tårnby - ID: 185
> 
> 34: Vejen - ID: 575

Jeg takker for svar. 

Ved du om kommunerne giver noget for det, for så ville jeg da foreslå Faxe forsyning at de kom med ind under den api. 

For de er på https://faxe.renoweb.dk/Legacy/selvbetjening/mit_affald.aspx

Må håbe min kommune snart bliver bedre it funktionelt.

**Comment by apollo14dk** [comment]
Hey Bjarne

Så skal du satme ikke høre et ondt ord, så smider jeg gerne en lille sjat penge, så du kan købe en god bøf 😁😁

**Comment by kentora** [comment]
Nu har dette issue lagt stille et stykke tid, men efter at være flyttet til en kommune der bruger /Legacy/ løsningen, tænkte jeg at jeg lige ville prøve at hive det ud. 

Når man går ind og tjekker afhentningsdage fyres et POST request af mod f.eks. https://faxe.renoweb.dk/Legacy/JService.asmx/GetAffaldsplanMateriel_mitAffald (Jeg bor ikke i Faxe, men har bare valgt en tilfældig adresse) med body
`{"adrid":33487,"common":false}` (common indgår nogle steder, ikke andre)

Svar kan så være:
`{
    "d": "{\"list\":[{\"id\":135714,\"materielnavn\":\"240 liter - Rest-/madaffald - tømmes hver 2. uge (1 stk.)\",\"ordningnavn\":\"Rest-/Madaffald\",\"toemningsdage\":\"Tirsdag lige uger\",\"toemningsdato\":\"Tirsdag den 20-09-2022\",\"pris\":\"1.248,00 kr.\",\"mattypeid\":26,\"antal\":1,\"vejnavn\":\"Teestrup Bygade\",\"modulsort\":-2147483648,\"adrid\":33487,\"fractionid\":5,\"viskalender\":true,\"afhentningsbestillingmateriel\":false,\"modulId\":1},{\"id\":156232,\"materielnavn\":\"240 liter - Genbrug MGP/PP - tømmes hver 4. uge (1 stk.)\",\"ordningnavn\":\"Genbrug\",\"toemningsdage\":\"Onsdag uge 3 (Genbrug)\",\"toemningsdato\":\"Onsdag den 07-09-2022\",\"pris\":\"Ingen\",\"mattypeid\":34,\"antal\":1,\"vejnavn\":\"Teestrup Bygade\",\"modulsort\":-2147483648,\"adrid\":33487,\"fractionid\":3,\"viskalender\":false,\"afhentningsbestillingmateriel\":false,\"modulId\":4},{\"id\":173078,\"materielnavn\":\"Storskrald - Torsdag uge 1 (1 stk.)\",\"ordningnavn\":\"Storskrald\",\"toemningsdage\":\"Torsdag uge 1 (Storskrald)\",\"toemningsdato\":\"Torsdag den 15-09-2022\",\"pris\":\"Ingen\",\"mattypeid\":99,\"antal\":1,\"vejnavn\":\"Teestrup Bygade\",\"modulsort\":-2147483648,\"adrid\":33487,\"fractionid\":6,\"viskalender\":false,\"afhentningsbestillingmateriel\":true,\"modulId\":2},{\"id\":204941,\"materielnavn\":\"Farligt affald - Torsdag uge 1 (1 stk.)\",\"ordningnavn\":\"Farligt affald\",\"toemningsdage\":\"Torsdag uge 1 (Farligt affald)\",\"toemningsdato\":\"Torsdag den 15-09-2022\",\"pris\":\"Ingen\",\"mattypeid\":120,\"antal\":1,\"vejnavn\":\"Teestrup Bygade\",\"modulsort\":-2147483648,\"adrid\":33487,\"fractionid\":9,\"viskalender\":false,\"afhentningsbestillingmateriel\":true,\"modulId\":6}]}"
}`

Jeg kan ikke helt regne ud hvor id'et kommer fra (Det stemmer ikke overens med ejendomsnr i UI), men det er relativt nemt at finde. Giver det mening at indarbejde i dette plugin, eller giver det mere mening at lave en "/Legacy/" udgave?

**Comment by briis** [comment]
> Nu har dette issue lagt stille et stykke tid

Ja, jeg er startet i nyt job, og har begrænset tid til at rode med dette.

Du skriver *Når man går ind og tjekker afhentningsdage fyres et POST request af mod f.eks.*. Hvor gør du dette hende? 
Hele søgemetoden virker ved at at der laves nogle *serielle* opslag, så man først finder Kommune ID, så finder man et Vej ID og så finder man Adresse ID. Det er det adresse id, sammen med Komme id, der er nøglen til at trække data ud.

Af ovenstående kan jeg se der faktisk kommer at Adresse ID, men hvis det adresse id kan så ikke bruges med den nuværende funktion, da det ikke returnerer data. Man kunne godt bygge et "legacy" modul ind i det eksisterende, men jeg ville ikke vide hvor jeg skulle få alle de Legacy URL'er fra. Har du fundet et sted de er samlet?

**Comment by kentora** [comment]
Nej, jeg har ikke fundet et sted de er samlet, og jeg tror ikke at det samme API kan bruges. Om det giver mening at lave et legacy modul i dette plugin ved jeg ikke, da jeg tror at hele opbygningen af data er anderledes.

Jeg har dog taget mig den frihed at prøve at lave et [plugin](https://github.com/kentora/renoweb-legacy) der henter data herfra. Hvis du men er det fornuftigt kan indarbejdes i dit plugin, fjerner jeg gerne mit igen 👍

**Comment by kentora** [comment]
(Det du har quoted mig for var i øvrigt ikke på nogen måde negativt ment, tillykke med nyt job 👏)

**Comment by apollo14dk** [comment]
> Nej, jeg har ikke fundet et sted de er samlet, og jeg tror ikke at det samme API kan bruges. Om det giver mening at lave et legacy modul i dette plugin ved jeg ikke, da jeg tror at hele opbygningen af data er anderledes.
> 
> 
> 
> Jeg har dog taget mig den frihed at prøve at lave et [plugin](https://github.com/kentora/renoweb-legacy) der henter data herfra. Hvis du men er det fornuftigt kan indarbejdes i dit plugin, fjerner jeg gerne mit igen 👍 

Damn det glæder jeg mig til at prøve. Så kan jeg endelig lade min HA skærm stå tændt.

**Comment by briis** [comment]
@kentora Jeg opfattede det bestemt ikke negativt, no worries.

Sad lige og kiggede det igennem du har lavet, og det ser super godt ud. Det giver ikke mening at prøve at integrere de to ting, i det mindste ikke lige nu. Jeg laver et link til dit Plugin på README filen, så folk der ikke kan få min integration til at virke, kan prøve med din. TAK.

**Comment by briis** [comment]
Så er der linket i README. Jeg lukker dette issue.
