### ISSUE TITLE
fra HA 2022.10.2

### ISSUE THREAD

**Issue by rhgiter** [briis/renoweb#15]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 16.47.27 (1 occurrences)
Last logged: 16.47.27

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for renoweb using this method at custom_components/renoweb/__init__.py, line 124: device_registry = await dr.async_get_registry(hass)

**Comment by briis** [comment]
Thought I had been through all my Integrations with the above issue, but must have missed this one 😁
Will be fixed.

**Comment by briis** [comment]
Just checked the releases are you sure you are running version 0.1.15? Because this warning has been fixed in that release, and was released back in May.
I also tested this on my own systems and I am not getting the error with either 2022.10.2 and 2022.11.dev

**Comment by rhgiter** [comment]
How do I see the version number  ?

![image](https://user-images.githubusercontent.com/61065752/195009584-eaeab287-42fb-4256-a770-65ec612ffeb7.png)

**Comment by briis** [comment]
If you have installed through HACS, just go to HACS and click on the Renoweb integration. You can then see the installed version number in the top left corner.

If not, the fastes way is to browse your `/config/custom_components/renoweb` directory and open the file `manifest.json` In this file look for version. It should say 0.1.15. If it does not update to the latest version and the warning should go away.

**Comment by rhgiter** [comment]
hi - I have HACS , but it was not under integration :-/ now I reinstalled it - its now updated and it seems to work without warnings --- thanks :-)
