### ISSUE TITLE
Unexpected error fetching renoweb data = Unavailable

### ISSUE THREAD

**Issue by elmdam87** [briis/renoweb#16]
Klokken 4:03:32 sker der en fejl og der logges 1.2 dage. Derefter er komponenten "Unavailable" indtil jeg reloader den.

Logger: custom_components.renoweb
Source: helpers/update_coordinator.py:164
Integration: RenoWeb Garbage Collection ([documentation](https://github.com/briis/renoweb), [issues](https://github.com/briis/renoweb/issues))
First occurred: 4:03:32 AM (1 occurrences)
Last logged: 4:03:32 AM

Unexpected error fetching renoweb data: 'list'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.10/site-packages/pyrenoweb/client.py", line 258, in get_pickup_data
    for row in json_data["list"]:
KeyError: 'list'

![image](https://user-images.githubusercontent.com/3354052/199191848-a868589f-cd95-46ee-a8f2-4280dfe1adf3.png)

**Comment by briis** [comment]
Jeg har selv set den fejl nogle gange. Det sker hvis integrationen af en eller anden årsag ikke kan få kontakt med serveren, så stopper den og skal manuelt genstartes. Jeg skal se om jeg kan få den til at prøve igen automatisk.

**Comment by mediaNen** [comment]
Jeg har præcis samme fejl. Sensorer er unavailable indtil jeg reloader integrationen.

**Comment by briis** [comment]
Jeg har frigivet V1.0.0 i dag som prøver at tage højde for at data nogen gange ikke kommer retur fra RenoWeb. I kan se release notes nedenfor.

- `ADDED`: For each Bin there will now be a binary_sensor called `binary_sensor.BIN_NAME_valid`. This sensor will show if data for this specific bin is valid. I use it personally with the conditional card, to only show a card if the data is valid.
- `CHANGED`: I have now rewritten some of the function to try and create more automatic recovery, should the sensor not get data on start on after an update. It will keep trying for a while, but if it takes too long it will give up, and not try again before the next timed update (Which per default is 6 hours). I did this a while ago and I do believe this introduces a **Breaking Change** as the sensors will get new names. (I honestly can't remember if this was the case) If this happens, just delete the Integration and re-add it, and then update you cards and automations with the new names. Sorry for any inconvinience.

**Comment by mediaNen** [comment]
> Jeg har frigivet V1.0.0 i dag som prøver at tage højde for at data nogen gange ikke kommer retur fra RenoWeb. I kan se release notes nedenfor.
> 
> * `ADDED`: For each Bin there will now be a binary_sensor called `binary_sensor.BIN_NAME_valid`. This sensor will show if data for this specific bin is valid. I use it personally with the conditional card, to only show a card if the data is valid.
> * `CHANGED`: I have now rewritten some of the function to try and create more automatic recovery, should the sensor not get data on start on after an update. It will keep trying for a while, but if it takes too long it will give up, and not try again before the next timed update (Which per default is 6 hours). I did this a while ago and I do believe this introduces a **Breaking Change** as the sensors will get new names. (I honestly can't remember if this was the case) If this happens, just delete the Integration and re-add it, and then update you cards and automations with the new names. Sorry for any inconvinience.

Efter opdateringen har jeg ikke længere udfald ser det ud til, tak :)

**Comment by briis** [comment]
> Efter opdateringen har jeg ikke længere udfald ser det ud til, tak :)

Lyder godt. Jeg lukker denne nu, og kommer det regelmæssigt igen, så bare genåben.
