### ISSUE TITLE
Dette RenoWeb service er ikke længere tilgængeligt

### ISSUE THREAD

**Issue by ThomasGNielsen** [briis/renoweb#17]
Integration starter med fejl: "Forsøger konfigurationen igen: Error requesting data from https://servicesgh.renoweb.dk/v1_13: 500, message='Internal Server Error"

Følger man linket https://servicesgh.renoweb.dk/v1_13: 500 i alm. browser, så kommer man til en side hos Renoweb, hvor der står: 

Dette RenoWeb service er ikke længere tilgængeligt
Vi beklager ulejligheden.
Opdater venligst til RenoMobil2

Kan du opdatere integrationen?

**Comment by Symbiot78** [comment]
samme her

**Comment by briis** [comment]
Jeg oplever ikke fejlen, og får fint data fra servicen. 

Men skulle de være i gang med at ændre alle referencer, kan det betyde at denne integration ikke vil virke mere. Det vil kræve at de nye adresser findes og token hentes ud. Det var ikke noget jeg gjorde i sin tid, jeg byggede ovenpå andre menneskers glimrende arbejde med at finde disse, og det er uden for mine kompetencer at gøre denne del.

**Comment by andrioid** [comment]
Prøvede for første gang i dag. Virkede fint.
