### ISSUE TITLE
Deprecated `async_get_registry`

### ISSUE THREAD

**Issue by JanHG** [briis/renoweb#18]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 14:16:29 (1 occurrences)
Last logged: 14:16:29

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for renoweb using this method at custom_components/renoweb/__init__.py, line 124: device_registry = await dr.async_get_registry(hass)

**Comment by briis** [comment]
Tror du mangler at opgradere din installation. V0.1.15 har fixet denne advarsel.
