### ISSUE TITLE
local variable 'min_friendly_name' referenced before assignment

### ISSUE THREAD

**Issue by istbarp** [briis/renoweb#19]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/renoweb/__init__.py", line 61, in async_setup_entry
    await renoweb.get_pickup_data()
  File "/usr/local/lib/python3.10/site-packages/pyrenoweb/client.py", line 342, in get_pickup_data
    "description": min_friendly_name,
UnboundLocalError: local variable 'min_friendly_name' referenced before assignment

**Comment by istbarp** [comment]
No news ? Seems this plugin is not working anymore? Maybe API Changed ?

**Comment by briis** [comment]
I don't have time right now to look at this. I can only say it works fine at my end. (Roskilde Kommune)

**Comment by istbarp** [comment]
> 

Prøver selv med Rebild Kommune. Kan være det er der fejlen er (altså i Rebild Kommune)

Man fair.

**Comment by StryxDK** [comment]
Har samme problem med rebild Kommune, har du fået det ly
øst istbarp?

**Comment by istbarp** [comment]
> Har samme problem med rebild Kommune, har du fået det løst istbarp?

Hey,
Nej, mit er også Rebild Kommune. Har prøvet båse med ældre plugin osv. Virker desværre ikke. Tænker der er tilføjet noget ekstra i api'et. 
Tror jeg vil give et kig på det i weekenden, og måske lave en pull request

**Comment by briis** [comment]
Som sagt kører det fint for mig med Roskilde kommune, men kan du finde noget, der er ændret, så bare lav en PR.

**Comment by StryxDK** [comment]
Blev du klogere på hvad der var galt i forhold til Rebild kommune?

> > Har samme problem med rebild Kommune, har du fået det løst istbarp?
> 
> Hey, Nej, mit er også Rebild Kommune. Har prøvet båse med ældre plugin osv. Virker desværre ikke. Tænker der er tilføjet noget ekstra i api'et. Tror jeg vil give et kig på det i weekenden, og måske lave en pull request

**Comment by istbarp** [comment]
![image](https://user-images.githubusercontent.com/6736441/227050890-36803448-d140-4d9d-b2a2-144f7d6b44c5.png)

Rebild er ikke længere nævnt som supported kommune.

**Comment by istbarp** [comment]
Kan se de er skiftet fra renoweb, til en app lavet af axla der hedder [affaldonline](https://www.affaldonline.dk/Rebild/)

Det har den konsekvens, at siden rebild ikke længere bruger renoweb, til at styre deres affaldsplaner, at denne integration ikke kommer til at virke. 

Har i den nye affaldonline som også har en app på play store der hedder "rebild affald" sat en notifikation op så den kommer på SMS dagen før kl 19. Ligesom jeg havde HA til at gøre for mig før. Men ja. Ikke helt det samme da jeg ikke kan bruge det i andre automationer. 

Jeg lukker dette issue. Tak for kigget dog Briis
