### ISSUE TITLE
Faxe Kommune is not avalibe

### ISSUE THREAD

**Issue by Striiter** [briis/renoweb#22]
hello.

Faxe Kommune is using renoweb, but is not available on the list.

Is it possible to add?

https://faxe.renoweb.dk/Legacy/selvbetjening/mit_affald.aspx

Thanks!

**Comment by briis** [comment]
Desværre er det ikke en mulighed. Det API jeg benytter understøtter kun nedenstående kommuner, og jeg kan ikke manuelt tilføje nogen. Jeg har set før at en Kommune benytter Renoweb, men de bruger så åbenbart ikke dette API til at levere data til borgerne. Beklager.

Hvilket API de så benytter ved jeg desværre ikke, og ej heller om der findes en anden løsning for dig.

```txt
MUNICIPALITY LIST
**************************
1: Aalborg - ID: 851
2: Allerød - ID: 201
3: BOFA TEST - ID: 400
4: Billund - ID: 530
5: Brøndby - ID: 153
6: Dragør - ID: 155
7: Egedal - ID: 240
8: Esbjerg - ID: 561
9: Fredensborg - ID: 210
10: Frederikssund - ID: 250
11: Gentofte - ID: 157
12: Gladsaxe - ID: 159
13: Glostrup - ID: 161
14: Greve - ID: 253
15: Halsnæs - ID: 260
16: Helsingør - ID: 217
17: Herlev - ID: 163
18: Hillerød - ID: 219
19: Hvidovre - ID: 167
20: Høje-Taastrup - ID: 169
21: Køge - ID: 259
22: Lejre - ID: 350
23: Lyngby-Taarbæk - ID: 173
24: Mariagerfjord - ID: 846
25: Ringkøbing-Skjern - ID: 760
26: Roskilde - ID: 265
27: Rudersdal - ID: 230
28: Rødovre Kommune - ID: 175
29: Samsø - ID: 741
30: Solrød - ID: 269
31: Svendborg - ID: 479
32: Sweco Demo - ID: 10210
33: Sweco Test D - ID: 20161
34: Sweco Test M - ID: 10730
35: Sweco Test R - ID: 16161
36: Tårnby - ID: 185
37: Vejen - ID: 575
````

**Comment by Striiter** [comment]
Hej Briis. Tak for dit hurtige svar!

Jeg forstår godt. :( Men sådan er det! Jeg er alligevel taknemlig for at andre har glæde af din hacs plugin! :D 

Vh.

**Comment by briis** [comment]
Hej @Striiter 
Jeg arbejder lige nu på en V2.0 der bruger et helt nyt API, og jeg har lige testet med et par tilfældige adresser i Faxe kommune, og det virker 😀. Hvis du er interreseret i at teste, så kan jeg give dig besked når der er noget klar til test.
