### ISSUE TITLE
Forkert adresse

### ISSUE THREAD

**Issue by nomad-cyanide** [briis/renoweb#23]
Hej

integrationen finder den forkerte adresse, når jeg taster min ind. Jeg taster dette ind:

Bruger nummer for Horsens, jævnfør dokumentationen.
Kommune: 615
Postnr.: 8700
Vej: Stensballevej
Nr. 2

Den finder husnr 2A, som er min nabo og vi har ikke samme skraldespande.

**Comment by briis** [comment]
Hej,
Den måde API henter data på er det ikke nemt, da alle huse, eksempelvis på din adresse, har samme husnummer. Forskellen på adresserne ligger i et ID nummer jeg ikke normalt bruger. Men jeg har nu lavet en workaround, så du kan få den rigtige adresse ind. 

Start med at installer V1.0.1 af Renoweb integrationen, og når du så skal skal oprette din adresse, så skriv 2,40648 i husnummeret, så vil den vælge din adresse og ikke 2A. (40648 er ID på netop dit hus, din nabo har et andet nummer)

Lad mig høre om det virker for dig.

**Comment by nomad-cyanide** [comment]
Det virkede, tak!! Men det er dælme ikke gjort nemt at arbejde med, kan jeg godt se. Man skulle tro at vejnavn og nummer var nok.....

**Comment by nomad-cyanide** [comment]
Det virkede, tak!! Men det er dælme ikke gjort nemt at arbejde med, kan jeg godt se. Man skulle tro at vejnavn og nummer var nok.....
