### ISSUE TITLE
When will 8210 be available?

### ISSUE THREAD

**Issue by kurtSejr** [briis/renoweb#25]
I'm living in "Aarhus" postcode 8210, when will this area be available in the integration.

**Comment by briis** [comment]
Det er desværre samme svar som i #22 
Det er ikke muligt manuelt at tilføje nogen kommuner.

Beklager

**Comment by kurtSejr** [comment]
Æv, men ok – tak for hurtig svar

 

/Kurt

 

Fra: Bjarne Riis ***@***.***> 
Sendt: 10. januar 2024 14:23
Til: briis/renoweb ***@***.***>
Cc: kurtSejr ***@***.***>; Author ***@***.***>
Emne: Re: [briis/renoweb] When will 8210 be available? (Issue #25)

 

Det er desværre samme svar som i #22 <https://github.com/briis/renoweb/issues/22> 
Det er ikke muligt manuelt at tilføje nogen kommuner.

Beklager
