### ISSUE TITLE
Problem with address 

### ISSUE THREAD

**Issue by Munkecut** [briis/renoweb#28]
**Describe the bug**
I have a problem with the address 

Sønderborg 
6400
Påkjær 27

It seems like it this the road which are not known, because it works with other addresses in the area without the special characters Æ and Ø
![Screenshot_20240121_202719_Home Assistant](https://github.com/briis/renoweb/assets/155022497/2462781b-c980-4a17-86cd-5cf921353656)

**Comment by briis** [comment]
Desværre er Sønderborg ikke understøttet af denne integration. Det er kun kommuner der er på [denne liste](https://github.com/briis/renoweb/blob/main/README.md#supported-municipalities) der er understøttet. Jeg kan ikke tilføje nogen til listen.
Kommunen bruger muligvis RenoWeb, men de har flere forskellige systemer, og denne understøtter kun et af dem.
