### ISSUE TITLE
Kan ikke finde adresse

### ISSUE THREAD

**Issue by thomaspalmdk** [briis/renoweb#39]
Kan ikke længere finde affaldskalender for min adresse.
Opsætning af ny adresse, eksempelvis ved at bruge min nabos adresse virker ikke.
Via renowebs hjemmeside kan jeg godt se affaldskalenderen.

Gå til
https://hillerod.renoweb.dk/Legacy/selvbetjening/mit_affald.aspx
Tast "Tværvej 1, 3320" (ikke min adresse, men en i samme område).
Herefter vises affaldskalender.

I Home Assistant i Renoweb-enheden tilføjer jeg en ny med følgende oplysninger:
Kommune: 219
Postnummer: 3320
Vej navn: Tværvej
Hus nummer: 1
(interval ikke relevant).

Med det samme får jeg et svar om at "den angivne adresse ikke blev fundet".

Jeg har også følgende fra indstillinger->system->log, her har jeg udeladt min adresse

```
Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 07.56.35 (3 occurrences)
Last logged: 15.04.59

Error setting up entry VEJNAVN HUSNUMMER, 3320 Skævinge for renoweb
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/renoweb/__init__.py", line 61, in async_setup_entry
    await renoweb.get_pickup_data()
  File "/usr/local/lib/python3.12/site-packages/pyrenoweb/client.py", line 275, in get_pickup_data
    for row in json_data["list"]:
               ~~~~~~~~~^^^^^^^^
KeyError: 'list'
```

Hvad dælen er der galt?

**Comment by briis** [comment]
Hej,
Når jeg kigger på den aktive liste af kommuner er Hillerød ikke længere blandt de kommuner der er understøttet. Jeg ved ikke præcis hvornår de er forsvundet, men det er inden for den sidste måned, da de var med sidst jeg opdaterede listen. Kommunen må være overgået til et andet af Renowebs API'er, som denne integration desværre ikke understøtter. Der er ikke rigtig noget jeg kan gøre ved det. Beklager.

Jeg har nu opdateret listen over aktive kommuner på forsiden.

**Comment by briis** [comment]
Det må du gerne Thomas. Jeg vil gerne prøve at se om vi kan få hul igennem til data.

**Comment by briis** [comment]
Jeg bruger nogle REST API'er, men jeg skal faktisk bruge min 2 kald til forskellige API'er med forskellige Tokens for at vi kan komme hele vejen rundt. De tokens jeg bruger er fundet af et par gæve guttere ved hjælp af Wireshark og APP eller webbroser på en Android telefon. Men det ligger uden for mine kompetancer. Tokens har dog heldigvis været de samme i al den tid denne Integration har eksisteret.

**Comment by briis** [comment]
Det ser spændende ud Thomas. Jeg prøver lige at eksperimentere lidt med dette på andre adresser, for at se om det virker for flere kommuner.
Men under alle omstændigheder, så finder jeg en måde at få dette ind i integrationen, så du kan få dine data igen.

**Comment by briis** [comment]
Er du logget ind når du foretager disse kald? Jeg får nemlig ikke data retur, men kun en logi ind side til Renoweb

**Comment by briis** [comment]
Doooh - Jeg havde lige glemt headeren i min test. Nu får jeg også resultater. Lad mig teste lidt på dette og se om jeg kan finde en god måde at strukturere dette i en Python Wrapper.

**Comment by briis** [comment]
En hurtig test: Hvis jeg erstatter `hillerod` med `roskilde`, og bruger det ID min applikation finder lige nu for min egen adresse, så virker det faktisk også. `https://roskilde.renoweb.dk/Legacy/JService.asmx/GetAffaldsplanMateriel_mitAffald`

Jeg kan dog ikke lige få søgningen til adresser til at virke for roskilde.

Nå, min kone siger jeg har en fuld kalender i dag, så der bliver ikke mere test idag, men jeg arbejder videre.

**Comment by briis** [comment]
Lige en kort status:

Jeg har haft lidt tid i dag og har nu stort set en ny Python Wrapper klar til de her nye API kald. Det betyder jeg kan finde adresse ID og derefter hente og aflevere tømningsdata.

Næste skridt vil være at tilrette selve Integrationen så den virker i Home Assistant. Jeg benytter lejligheden til at omskrive det hele, da der er sket rigtig meget i Home Assistant siden jeg startede med dette. Det betyder også at det ikke vil være bagud-kompatibel (Hvilket du jo nok er ligeglad med 😀). Jeg vil bl.a. se om jeg kan få lagt datoerne ind i en lokal HA kalender, hvilket gør det nemt at lave automatiseringer.

Jeg ved ikke præcis hvornår jeg har noget klar til test, men du hører nærmere her.

**Comment by briis** [comment]
Super. Jeg får rettet det med plast/metal. Jeg prøver at pulje containerne lidt for sikre jeg nemt kan opdatere NÅR politikkerne nu finder på noget andet. 

Kalender delen driller da jeg aldrig har lavet en sådan, men jeg får det nok fixet. Tager det længere tid, kan duft lov og teste bare med sensorer. 

Godt at høre du ikke mangler mere data, det gør det lidt nemmere.

**Comment by briis** [comment]
Hej Thomas,
Dette bliver den sidste status inden du kan teste 😀
Jeg har nu en kørende version med både sensorer og en lokal kalender, og som du kan se på skærmbilledet, så har jeg også lagt `entity_picture` ind på alle typer, så det kan se lidt lækre ud. Desværre kan man ikke i en Custom Component, lægge disse på plads under installationen, så de skal lige kopieres manuelt over under www/renoweb inden man starter.

Jeg har det kørende her, og mangler nu kun at opdatere dokumentationen, så man ved hvad der skal gøres for at opgradere.
Hvis alt går vel, slipper jeg Beta 1 på lørdag, så kan du også teste og komme med feedback.

![Skærmbillede 2024-02-29 kl  18 50 34](https://github.com/briis/renoweb/assets/24776272/5ad422cb-9697-4678-915b-ca1775fe0bf7)

**Comment by briis** [comment]
Hej Thomas,
Så er jeg klar til du tester 😀
Læs [denne dokumentation](https://github.com/briis/renoweb/blob/version2-0-0/README.md) og se om du kan finde ud af at køre opgradering/installationen ud fra min beskrivelse. Hvis der er noget uklart eller det ikke virker, lad mig det vide.

**Comment by rhgiter** [comment]
Hej, 
Det virker for mig i Hillerød, postnummer 3320
![image](https://github.com/briis/renoweb/assets/61065752/d613df50-c778-4fac-b1f9-eb71737a19ca)
Mange tak. :-)

**Comment by briis** [comment]
Nu tog jeg lige en tilfældig adresse i Skævinge og her fik en Plast og Madkartoner tømning. Hvis du kunne give mig det vejnavn og nummer ved at sende til mig det på email (eller skrive det her), så kan jeg lige undersøge hvorfor den ikke kommer med. email er bjarne@briis.com

**Comment by briis** [comment]
Super, det ser jo godt ud. Jeg har fixet problemet med den manglende sensor. Sender Beta2 ud i morgen hvor det er med.

**Comment by briis** [comment]
Så har jeg sluppet Beta 2, som gerne skulle fixe den manglende Container for Hillerød Kommune. 

En tanke: Når man nu alligevel skal slette det gamle for at installere V2, så overvejer at give det hele et nyt domain navn, eksempelvis `affalddk`i stedet for `renoweb`- Årsagen er at Renoweb jo er et varemærke og jeg har ingen rettigheder til at benytte det, og det er også derfor jeg ikke har lagt det i default HACS store, da det krævet et Logo, som jeg heller ikke har rettigheder til. Med det nye navn, kan jeg bare lave et selv, og så få lagt Integrationen i Default HACS store.

Det vil betyde at de der har installeret V2 Beta, skal fjerne den og installere igen, men tilgengæld vil V1.x af Renoweb og den nye version kunne sameksistere, så man har lidt tid til at migrere.

Nogen kommentarer til det?

**Comment by rhgiter** [comment]
Tak, så kom plast med i Hillerød kommune :-)

Personligt er jeg ligeglad med navnet, men synes det var en større fordel af den kom med i default HACS, især også for nye brugere. Jeg mindes da jeg startede og endelig havde "kæmpet" med at installere HACS , så forstod jeg ikke at noget skulle indstalleres uden om Hacs alligevel.

**Comment by briis** [comment]
Jeg endte med at ændre navnet, og den endelige integration er nu klar. Gå over til https://github.com/briis/affalddk og få den installeret. HUSK: I skal afinstallere denne Renoweb integration først, fjerne den fra HACS og genstarte Home Assistant før i installerer.

Den skal lige nu også tilføjes manuelt til HACS, men jeg er gået i gang med at lave en PR så den kan komme med i Default Store. Erfaringen viser dog det kan tage 6-8 uger.

Tak for hjælpen med at teste.
