### ISSUE TITLE
Kan man få 8700 med?

### ISSUE THREAD

**Issue by jsachman** [briis/renoweb#4]

**Comment by briis** [comment]
Ved du om I bruger Renoweb i Horsens Kommune?

**Comment by jsachman** [comment]
Jeps, ledte efter integrationen da jeg kan de det er renoweb der indeholder
renovation spanierne.



lør. 21. nov. 2020 19.59 skrev Bjarne Riis <notifications@github.com>:

**Comment by jsachman** [comment]
Pokkers til stavekontrol... Renovationsplanerne skulle der stå...

**Comment by briis** [comment]
Hvis du skriver dit post nummer og vejnavn så kan jeg tjekke

**Comment by jsachman** [comment]
Mange tak. Det er:

Krogen 4
8700 Horsens

søn. 22. nov. 2020 07.54 skrev Bjarne Riis <notifications@github.com>:

**Comment by briis** [comment]
Så fandt jeg det. Når du tilføjer integration så skriver du **615** i Kommune feltet i stedet for Horsens, så burde det virke.
Luk dette issue, hvis det virker for dig.

**Comment by jsachman** [comment]
Super, Bjarne. 1.000 tak, kigger lidt senere på dagen.

Jesper

**Comment by jsachman** [comment]
Virker perfekt

**Comment by jsachman** [comment]
Tak
