### ISSUE TITLE
Opdatere på bestemt tidspunkt ?

### ISSUE THREAD

**Issue by Boss-man** [briis/renoweb#42]
**Is your feature request related to a problem? Please describe.**
Jeg sender en besked til min telefon om morgenen hvis jeg skal sætte skrald ud.
Har sat integrationen til at opdatere hver 5 time, men alligevel opdatere den nogen gange først efter kl. 8.
Jeg får derfor ikke nogen besked på min telefon fordi integration stadig siger der er 1 dag til der afhentes skrald.

I dag er den f.eks først opdateret 8.57, og der er jeg allerede kørt på arbejde.

**Describe the solution you'd like**
Vil det være muligt at sætte et bestemt tidspunkt den skal hente data ? F.eks kl. 1 om natten
Alternativt kan jeg sætte integration til at opdatere oftere, men der er ingen grund til jeg henter data i løbet af dagen. 
Ved ikke hvornår data er opdateret i renoweb.

**Comment by briis** [comment]
Hej,
Den burde opdatere hver 5. time når det er det du har sat den til, men hvis den ikke kan hente data fordi API ikke svarer, så prøver den nogle gange inden for de næste minutter. Lykkes det stadig ikke venter den 5 timer igen.
Problemet med det API denne udgave bruger er at RenoWeb er ved at udfase det, så jeg ved ikke hvor meget de passer det.
Jeg er pt. i gang med at lave en helt ny version, der bruger det samme API som kommunerne bruger i deres portaler, her burde det være mere stabilt. Jeg laver også en sensor som giver dig tiden for sidste opdatering, den kan du så eventuelt også tjekke i din automatisering.

Udover sensorerne, så får du også en lokal kalender med de enkelte afhentninger i, den vil automatisk skifte status ved midnat, når afhentning foregår. Her kan du så lave en automatisering hvor du tjekker på et bestemt tidspunkt hver dag og hvis kalenderen er On, så er der en afhentning.

Jeg satser på at have en Beta 1 klar senest i weekenden.

**Comment by briis** [comment]
Beta 1 er klar nu, men læs lige dette grundigt inden du gør noget: https://github.com/briis/renoweb/tree/version2-0-0

Men under alle omstændigheder, hvis du vil være sikker på din sensor er opdateret på et bestemt tidpunkt, så kan du starte en opdatering af data ved at køre nedenstående service. Den kunne ligges ind i en automatisering og køre på et bestemt tidspunkt hver morgen. Bare en tanke.

```yaml
service: homeassistant.reload_config_entry
data: {}
target:
  entity_id: sensor.renoweb_days_until_next_pickup
```

**Comment by Boss-man** [comment]
Tak, det vil jeg se på når jeg lige får ro til det.
