### ISSUE TITLE
Næstved Kommune

### ISSUE THREAD

**Issue by outlooknerd** [briis/renoweb#5]
Jeg kan se at Næstved Kommune bruger renoweb og kalder https://naestved.renoweb.dk/Legacy/JService.asmx/GetAffaldsplanTakst_mitAffald for at få en affaldsplan, som returnerer adrid=24071.

Men jeg kan ikke få integrationen til at køre, da den siger at Næstved ikke findes, og jeg kan heller ikke sniffe mig frem til id for kommunen.

Vil det være muligt at ændre integrationen, så man kan angive et direkte adrid?

**Comment by briis** [comment]
Problemet er at nogle kommuner ikke findes i oversigten, og derfor skal man manuelt finde kommune id, som så bruges når man sætter det op.
Hvis du giver mig post nummer og vejnavn, så har jeg et lille program der kan gøre arbejdet for mig.
Hvis du kigger på kommune oversigten på forsiden af dette repository, og skriver den by der ligger tættest på, så kan jeg indsnævre søgningen.

**Comment by outlooknerd** [comment]
Så får du lige to adresser med det samme i samme kommune ;-)

Vigen 17, 4736 Karrebæksminde
Realskolevej 6, 4171 Glumsø

Begge ligger i Næstved kommune, som har postnummer 4700.

**Comment by outlooknerd** [comment]
Fandt lige løsningen selv. Hvis man går ind og kalder dette api: https://dawa.aws.dk/kommuner, så kan man se alle kommuner, og her kunne jeg søge Næstved frem, som har id 370. Kan være du skal inkludere dette tip i dokumentationen.

**Comment by briis** [comment]
Cool. Jeg tror faktisk jeg bruger dette websted til at finde kommunen i, i stedet for det jeg bruger nu, da dette jo ser komplet ud. Tak for det.

**Comment by briis** [comment]
Jeg lukker denne. Tak for hjælpen med at finde den komplette kommune side
