### ISSUE TITLE
Support for HACS

### ISSUE THREAD

**Issue by ZenithDK** [briis/renoweb#6]
Could you add support for HACS?
That would make installing this repository a lot easier.

Thanks for your work!

**Comment by briis** [comment]
Hej Lasse,
Der er support for HACS. Da det er et meget snævert produkt har jeg ikke brugt tid på at lægge det ind i default HACS store, men du kan lægge det ind i Custom Repositories i HACS. (Sig til hvis du ikke ved hvordan). Brug adressen https://github.com/briis/renoweb og vælg Category Integrations.

**Comment by ZenithDK** [comment]
Jeg læser tydeligvis helt vildt dårligt - beklager, spottede det lige efter at have lavet issuet.
