### ISSUE TITLE
Haveaffald -1 dag

### ISSUE THREAD

**Issue by kejXero** [briis/renoweb#7]
sensor sensor.renoweb_haveaffald viser -1 dag. Og har gjort det vinteren over. Jeg troede egentlig at den ville "vågne" op igen her til foråret. Men som skrevet så viser den -1 dag. Nogen gode råd?

**Comment by briis** [comment]
Jeg havde det samme med min metal/glas container, der kun bliver tømt hver 2. måned. I næsten 2 måneder stod den til -1, som er den værdig jeg sætter, når der ikke er en gyldig dato leveret i API.
Prøv at logge ind på kommunens hjemmeside, og se hvad der står af dato ud for have affald - det kan give os en indikation på om der er en fejl i denne integration, eller det blot er kommunen der ikke opdaterer data.

**Comment by kejXero** [comment]
Hej Bjarne,

Tak for din tilbagemelding.

Når jeg logger ind på Gladsaxe Kommunes RenoWeb Oversigt over affald<https://gladsaxe.renoweb.dk/Legacy/selvbetjening/mit_affald.aspx>, ser det ud som nedenstående skema.

Jeg ved ikke om min udfordring opstår fordi have affaldet er oplistet 3 gange?

[cid:image001.png@01D7142A.BB195320]


Nedenstående figurer er når jeg har foldet dropdown menuen ud. To af dem har datoer, men den sidste har ingenting.
[cid:image002.png@01D7142B.451E4580]

Figur 1 Haveaffald, flishugning              Haveaffald (1 stk.)  Tirsdag Have lige uger
[cid:image003.png@01D7142B.451E4580]

Figur 2 Haveaffald, flishugning              Have - 660 l beholder (1 stk.) Tirsdag Have lige uger

[cid:image004.png@01D7142B.451E4580]

Figur 3 Haveaffald, flishugning              Flishugning (1 stk.)

Med venlig hilsen

Henrik Næsby

**Comment by briis** [comment]
Hej Henrik
Jeg kan ikke se de billeder du har uploaded. Kunne du prøve igen. Alternativt hvis du vil, så PM mig din adresse så kan jeg prøve at se hvad der kommer ud af API'et direkte. Du kan maile på bjarne@briis.com

**Comment by briis** [comment]
Hej Henrik,
Dette er de data jeg får ud når jeg trækker direkte på din adresse. Som du kan se under haveaffald, så er der ingen planlagte tømninger og datoen står til den 1. januar 2020, så derfor vil den være -1. 
Havde du forventet noget andet?

```log
PICK-UP'S
**************************

TYPE: Storskrald
DESCRIPTION: Pap 240 l
NEXT PICK-UP: Tirsdag d. 30-03-2021
DATE: 2021-03-30
SCHEDULE: Hver 4. tirsdag uge 1,5,9,13,17,21,25,29,33,37,41,45,49
DAYS TO PICK-UP: 22

TYPE: Haveaffald
DESCRIPTION: Flishugning
NEXT PICK-UP: Ingen planlagte tømninger
DATE: 2020-01-01
SCHEDULE: 
DAYS TO PICK-UP: -1

TYPE: Glas/Papir
DESCRIPTION: Papir og glas
NEXT PICK-UP: Tirsdag d. 23-03-2021
DATE: 2021-03-23
SCHEDULE: Hver 4. tirsdag uge 4,8,12,16,20,24,28,32,36,40,44,48,52
DAYS TO PICK-UP: 15

TYPE: Plast/Metal
DESCRIPTION: Plast og metal 240 ltr.
NEXT PICK-UP: Tirsdag d. 23-03-2021
DATE: 2021-03-23
SCHEDULE: Hver 4. tirsdag uge 4,8,12,16,20,24,28,32,36,40,44,48,52
DAYS TO PICK-UP: 15

TYPE: Dagrenovation
DESCRIPTION: 240 liter mad og rest
NEXT PICK-UP: Tirsdag d. 09-03-2021
DATE: 2021-03-09
SCHEDULE: Tirsdag mad og rest (lige)
DAYS TO PICK-UP: 1
```

**Comment by briis** [comment]
Hej igen,
Ja fejlen er at Haveaffald optræder 3 gange med dette navn, og det gør at det kun er den sidste der kommer med, da den overskriver det array, jeg laver. Jeg må lige finde en måde at omgåes det på, så det ikke ødelægger det for andre der har installeret modulet.

**Comment by briis** [comment]
Hej Henrik,
Så jeg har jeg fixet det. Desværre giver det en BREAKING CHANGE, da jeg er nød til at give sensorerne et nyt unique id for at kunne holde dem adskilte. I praksis betyder det at du skal slette den eksisterende integration, og så tilføje den igen. Så skal du finde sensorerne og rette navnene i Lovelace. Ville være fint du kunne teste det for mig inden jeg frigiver.

Hvis du downloaded `entity.py` og `manifest.json` fra custom_components biblioteket i dette Githib, og så overskriver dem du har i din Home Assistant mappe. Genstart så HA, og slet/tilføj integrationen igen.

**Comment by kejXero** [comment]
Jeg har overskrevet de to filer med de nye. Skal jeg så afinstallere RenoWeb Garbage Collection intergrationen for derefter at installere den igen?

**Comment by kejXero** [comment]
Nu slettede jeg integrationen genstartede, og kan ikke finde Renoweb som integration.. Nogen tricks?

**Comment by kejXero** [comment]
geninstallerede integrationen og nu kunne jeg se den :) men resultatet er det samme, haveaffald står til -1 dag igen.

**Comment by kejXero** [comment]
Jeg har ikke fået flere eller nye sensorer, stadig de samme 5 som før

**Comment by briis** [comment]
Hej Henrik,
Ja beklager lidt forvirrende. Hvis du har geninstalleret, så er de 2 filer du overskrev, blev overskrevet tilbage, så gør følgende:
* Overskriv de to filer i den installation du har nu
* Genstart Home Assistant
* Gå til Integrations siden, og find Renoweb Integration, som skulle være på siden sammen med andre ting du måtte have installeret
* Klik på de tre prikker i bunden til højre og vælg Slet
* Klik så på +Tilføj Integration, og tilføj Renoweb igen - indtast dine informationer, og du skulle gerne se dette:

<img width="393" alt="Skærmbillede 2021-03-08 kl  18 31 59" src="https://user-images.githubusercontent.com/24776272/110358844-15adbc80-803d-11eb-894f-2b9662433a24.png">

Så du får stadig den med -1 (Tror det er en kommunen mangler at fjerne), men du får også 2 nye med data i.

**Comment by kejXero** [comment]
Tak for svar. Jeg har overskrevet de to filer, slettet integrationen, men jeg kan ikke finde Renoweb igen når jeg søger med "pluset" i højre hjørne

**Comment by briis** [comment]
Du slettede den fra Integrations siden ikke? Ikke i HACS?
Hvis det var det første, så prøv lige at lave en Hard Refresh af din browser, så plejer det at dukke op igen.

**Comment by kejXero** [comment]
jeps inde fra integrations siden. Hard reset? er det shift F5 eller hvordan?

**Comment by briis** [comment]
Ja, det afhænger lidt af Browseren. Jeg bruger Mac, så i Safari er den Cmd+R.

**Comment by kejXero** [comment]
jeg har prøvet crtl+F5, shift+crtl+R but still no luck

**Comment by briis** [comment]
Hmmm... Tjek lige at du stadig har et bibliotek med filerne i `custom_components/renoweb` i Home Assistant

**Comment by kejXero** [comment]
![image](https://user-images.githubusercontent.com/63678121/110360651-48f14b00-803f-11eb-90cb-dae15dd29a31.png)

**Comment by briis** [comment]
OK, så forstår jeg ikke du ikke kan finde Integrationen. I sær hvis du bare slettede den, og så prøvede at tilføje den igen med det samme. Prøv lige at genstarte HA igen, og så om du kan så.

**Comment by kejXero** [comment]
har lige genstartet, uden held.

**Comment by kejXero** [comment]
hvis jeg sletter/reinstallere fra HACS så kunne jeg godt finde den igen, så var det forfra som jeg forstod det.

**Comment by briis** [comment]
Problemet er at det der ligger på HACS, er det samme som du havde før. Men hvis du prøver at installere fra HACS, og så før du genstarter, så overskriver de 2 filer. Så kan det være du kan finde den.

Vi er enige om at du ser det første skræmbillede:
<img width="497" alt="Skærmbillede 2021-03-08 kl  18 57 40" src="https://user-images.githubusercontent.com/24776272/110361527-7094e300-8040-11eb-9d98-9a41a1ef4c00.png">

Men du ser ikke dette når du søger efter Renoweb:

<img width="497" alt="Skærmbillede 2021-03-08 kl  18 58 03" src="https://user-images.githubusercontent.com/24776272/110361577-80acc280-8040-11eb-9ef4-cc7d947c5458.png">

**Comment by kejXero** [comment]
![image](https://user-images.githubusercontent.com/63678121/110361705-aa65e980-8040-11eb-8fa7-e1f1497cd468.png)

**Comment by kejXero** [comment]
![image](https://user-images.githubusercontent.com/63678121/110361771-c2d60400-8040-11eb-8645-de823f03b372.png)

**Comment by briis** [comment]
Det er sgu mærkeligt, men det er typisk et caching problem. Nå prøv at installere igen via HACS, og så overskriv de 2 filer INDEN du genstarter.

**Comment by kejXero** [comment]
det prøver jeg nu

**Comment by kejXero** [comment]
Det virker ikke med en "kombi" metode. Jeg kan stadig ikke finde Renoweb igen. Jeg har tampet på ctrl+F5

**Comment by briis** [comment]
Jeg har lavet en HCAS release der hedder V0.1.12-beta-1. Den indeholder de rigtige filer.
Kan du prøve at installere den fra HACS?

**Comment by kejXero** [comment]
Slettede via HACS, genstartede HA. Jeg kan ikke se version 1.12-beta-1.

![image](https://user-images.githubusercontent.com/63678121/110364773-7c82a400-8044-11eb-8f3f-330b6b22fcec.png)

**Comment by kejXero** [comment]
nu kom den

**Comment by kejXero** [comment]
Så ruller vi :)

![image](https://user-images.githubusercontent.com/63678121/110366633-d84e2c80-8046-11eb-88e0-99c0a6be6fc2.png)

**Comment by briis** [comment]
Fedt. Så tjekker jeg lige det sidste, og frigiver den officielt i morgen.

**Comment by briis** [comment]
Nu officielt frigivet som v0.1.13
