### ISSUE TITLE
Rødovre kommune (virker)

### ISSUE THREAD

**Issue by cnrd** [briis/renoweb#9]
Hej

Selvom den ikke fremgår af listen, så virker Rødovre kommune og der returneres data for alle de samme entries som findes på rk.renoweb.dk

**Comment by briis** [comment]
Hej Conrad, 
Tak for oplysningen. Kan du give mig kommune ID, så opdaterer jeg listen.

**Comment by cnrd** [comment]
0175

**Comment by briis** [comment]
Det er også det rigtige. Listen er nu opdateret. Tak.
